title: Chinmay Naik
email: chinmay185@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Chinmay's blog - musings on software development and lessons learnt.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://chinmaynaik.in" # the base hostname & protocol for your site
twitter_username: chinmay185
github_username:  chinmay185
markdown: kramdown
